"""Shared configuration constants for the training pipeline."""

BOARD_WIDTH = 10
BOARD_HEIGHT = 40
BOARD_CELLS = BOARD_WIDTH * BOARD_HEIGHT

NUM_PIECE_TYPES = 7
QUEUE_LENGTH = 5
HOLD_PIECE = 1
CURRENT_PIECE = 1
PIECE_ONE_HOTS = NUM_PIECE_TYPES * (QUEUE_LENGTH + HOLD_PIECE + CURRENT_PIECE)

NUM_SCALARS = 5

PLAYER_BOARD_FEATURES = BOARD_CELLS
OPPONENT_BOARD_FEATURES = BOARD_CELLS
TOTAL_FEATURES = (
    PLAYER_BOARD_FEATURES
    + OPPONENT_BOARD_FEATURES
    + PIECE_ONE_HOTS
    + NUM_SCALARS
)

STUDENT_DIMS = [TOTAL_FEATURES, 192, 96, 48]
NUM_REGRESSION_HEADS = 6
NUM_PHASE_CLASSES = 3
STUDENT_OUTPUT_DIM = NUM_REGRESSION_HEADS + NUM_PHASE_CLASSES

MOVE_FEATURE_DIM = 14
POLICY_VALUE_STATE_DIMS = [TOTAL_FEATURES, 256, 128]
POLICY_VALUE_MOVE_DIMS = [MOVE_FEATURE_DIM, 64]

TEACHER_CHANNELS = [64, 128, 256]
TEACHER_FC_DIM = 512

OPENER_BAG_CUTOFF = 4
PIECES_PER_BAG = 7

DEFAULT_BATCH_SIZE = 2048
DEFAULT_LR = 1e-3
DEFAULT_WEIGHT_DECAY = 1e-4
DEFAULT_EPOCHS = 100
PIECES_PER_BAG = 7

FEATURES_PER_SAMPLE = TOTAL_FEATURES
LABELS_PER_SAMPLE = 5
FLOATS_PER_SAMPLE = FEATURES_PER_SAMPLE + LABELS_PER_SAMPLE
BYTES_PER_SAMPLE = FLOATS_PER_SAMPLE * 4

REGRESSION_HEAD_NAMES = [
    "value",
    "attack_potential",
    "defensive_solidity",
    "efficiency",
    "flexibility",
    "tempo",
]

PHASE_CLASS_NAMES = [
    "opener",
    "midgame",
    "survival",
]

WEIGHT_EXPORT_ORDER = [
    ("hidden.linear0.weight", (192, TOTAL_FEATURES)),
    ("hidden.linear0.bias", (192,)),
    ("hidden.linear1.weight", (96, 192)),
    ("hidden.linear1.bias", (96,)),
    ("hidden.linear2.weight", (48, 96)),
    ("hidden.linear2.bias", (48,)),
    ("output.weight", (STUDENT_OUTPUT_DIM, 48)),
    ("output.bias", (STUDENT_OUTPUT_DIM,)),
]
